package procgen

import (
	"bytes"
	"image"
	_ "image/jpeg"
	_ "image/png"
	"log"
	"math/rand"

	"github.com/automoto/doomerang/assets"
	"github.com/hajimehoshi/ebiten/v2"
)

// decorationSeedOffset is added to the level seed to give decoration its own RNG stream,
// independent of the layout RNG which uses the seed directly.
const decorationSeedOffset int64 = 1

// backgroundVariants maps biome names to embedded asset paths for background images.
// Paths are relative to the embedded FS root (within the "levels" directory).
var backgroundVariants = map[string][]string{
	// Only use the 1920x1080 low-detail images — detailed cityscapes distort badly
	// when scaled to level height. bg-cyberpunk-large.png excluded for this reason.
	"cyberpunk": {
		"levels/background/Background-Night.png",
		"levels/background/Background-Night-Complete-2-Blurred-.png",
	},
	"industrial": {
		"levels/background/cyber-bg-dark.jpg",
	},
	"neon": {
		"levels/background/cyber-bg.jpg",
	},
}

// biomeTints maps each biome to characteristic multiplicative RGB tint presets.
// Values close to 1.0 keep the tint gentle; asymmetry in RGB channels shifts the hue.
var biomeTints = map[string][][3]float32{
	"cyberpunk": {
		{1.00, 1.00, 1.00}, // neutral
		{0.70, 0.50, 1.00}, // purple haze
		{0.50, 1.00, 0.70}, // neon green
	},
	"industrial": {
		{1.00, 0.70, 0.50}, // warm amber
		{1.00, 0.85, 0.65}, // soft gold
		{0.85, 0.75, 0.65}, // dusty
	},
	"neon": {
		{0.50, 0.70, 1.00}, // cool blue
		{0.70, 0.50, 1.00}, // purple haze
		{1.00, 0.50, 0.80}, // magenta
	},
}

// defaultTint is used when a biome has no entry in biomeTints.
var defaultTint = [3]float32{1.00, 1.00, 1.00}

// DecorationOptions carries the visual variation choices for a single run.
type DecorationOptions struct {
	// BackgroundImage is tiled horizontally behind the tile layers. May be nil.
	BackgroundImage *ebiten.Image
	// TintR/G/B are multiplicative RGB scale factors applied when drawing the background image.
	TintR, TintG, TintB float32
}

// DeriveDecoration picks a background variant and color tint deterministically from seed + biome.
// Uses a separate RNG stream (XOR with magic constant) so decoration choices are independent of
// the level layout generated by the main RNG.
func DeriveDecoration(seed int64, biome string) DecorationOptions {
	rng := rand.New(rand.NewSource(seed + decorationSeedOffset))

	opts := DecorationOptions{TintR: 1, TintG: 1, TintB: 1}

	if variants, ok := backgroundVariants[biome]; ok && len(variants) > 0 {
		chosen := variants[rng.Intn(len(variants))]
		opts.BackgroundImage = loadBackgroundImage(chosen)
	}

	if tints, ok := biomeTints[biome]; ok && len(tints) > 0 {
		tint := tints[rng.Intn(len(tints))]
		opts.TintR, opts.TintG, opts.TintB = tint[0], tint[1], tint[2]
	} else {
		opts.TintR, opts.TintG, opts.TintB = defaultTint[0], defaultTint[1], defaultTint[2]
	}

	return opts
}

// loadBackgroundImage reads an image from the embedded asset FS. Returns nil on failure.
func loadBackgroundImage(path string) *ebiten.Image {
	fs := assets.GetAssetFS()
	data, err := fs.ReadFile(path)
	if err != nil {
		log.Printf("procgen: background image not found %q: %v", path, err)
		return nil
	}
	img, _, err := image.Decode(bytes.NewReader(data))
	if err != nil {
		log.Printf("procgen: failed to decode background image %q: %v", path, err)
		return nil
	}
	return ebiten.NewImageFromImage(img)
}
